In [16]:
#use numpy, pandas package
import numpy as np 
import pandas as pd

#read the csv file 
data1 = pd.read_csv('6ef495654a3afcaa.csv')
data1

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,xoptdqp,xopteps12,xoptepsp12,xoptepsq,xoptepsqp,xoptq,xoptqp,xrdq,xsgaq,costat
0,1076,20100331,2010,1,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,194.930,A
1,1076,20100630,2010,2,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,195.503,A
2,1076,20100930,2010,3,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,194.246,A
3,1076,20101231,2010,4,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,193.944,A
4,1076,20110331,2011,1,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,201.842,A
5,1076,20110630,2011,2,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,199.784,A
6,1076,20110930,2011,3,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,206.088,A
7,1076,20111231,2011,4,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,208.170,A
8,1076,20120331,2012,1,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,221.460,A
9,1076,20120630,2012,2,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,224.673,A
10,1076,20120930,2012,3,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,220.767,A
11,1076,20121231,2012,4,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,228.579,A
12,1076,20130331,2013,1,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,235.614,A
13,1076,20130630,2013,2,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,235.868,A
14,1076,20130930,2013,3,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,245.490,A
15,1076,20131231,2013,4,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,248.696,A
16,1076,20140331,2014,1,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,248.638,A
17,1076,20140630,2014,2,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,287.157,A
18,1076,20140930,2014,3,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,300.081,A
19,1076,20141231,2014,4,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,310.325,A
20,1076,20150331,2015,1,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,307.976,A
21,1076,20150630,2015,2,12,INDL,C,D,STD,AAN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,305.743,A
22,1076,20150930,2015,3,12,INDL,C,D,STD,AAN,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,321.590,A
23,1076,20151231,2015,4,12,INDL,C,D,STD,AAN,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,334.666,A
24,1076,20160331,2016,1,12,INDL,C,D,STD,AAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,323.998,A
25,1076,20160630,2016,2,12,INDL,C,D,STD,AAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,310.388,A
26,1076,20160930,2016,3,12,INDL,C,D,STD,AAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.341,A
27,1076,20161231,2016,4,12,INDL,C,D,STD,AAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,319.997,A
28,1076,20170331,2017,1,12,INDL,C,D,STD,AAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.185,A
29,1076,20170630,2017,2,12,INDL,C,D,STD,AAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,310.886,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803,18320,20110331,2011,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,A
3804,18320,20110630,2011,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,A
3805,18320,20110930,2011,3,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,A
3806,18320,20111231,2011,4,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,9.750,29.086,A
3807,18320,20120331,2012,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.376,7.504,A
3808,18320,20120630,2012,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.393,8.249,A
3809,18320,20120930,2012,3,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.427,7.800,A
3810,18320,20121231,2012,4,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.531,7.807,A
3811,18320,20130331,2013,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.355,8.312,A
3812,18320,20130630,2013,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.587,8.881,A
3813,18320,20130930,2013,3,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.500,9.219,A
3814,18320,20131231,2013,4,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.967,9.258,A
3815,18320,20140331,2014,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.135,9.884,A
3816,18320,20140630,2014,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.625,12.798,A
3817,18320,20140930,2014,3,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.468,12.756,A
3818,18320,20141231,2014,4,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.414,12.066,A
3819,18320,20150331,2015,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.402,12.798,A
3820,18320,20150630,2015,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,4.158,15.009,A
3821,18320,20150930,2015,3,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.641,16.257,A
3822,18320,20151231,2015,4,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800,15.763,A
3823,18320,20160331,2016,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.392,16.558,A
3824,18320,20160630,2016,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.582,17.920,A
3825,18320,20160930,2016,3,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.724,18.072,A
3826,18320,20161231,2016,4,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.761,18.573,A
3827,18320,20170331,2017,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.482,19.032,A
3828,18320,20170630,2017,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.982,19.877,A
3829,18320,20170930,2017,3,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.545,21.115,A
3830,18320,20171231,2017,4,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.169,21.324,A
3831,18320,20180331,2018,1,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.197,23.751,A
3832,18320,20180630,2018,2,12,INDL,C,D,STD,FOXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.057,26.333,A

In [17]:
#drop the meaningless column
data2 = data1.drop(['gvkey','datadate','fyearq','fqtr','fyr'],axis =1)
data2

,indfmt,consol,popsrc,datafmt,tic,curcdq,datacqtr,datafqtr,acchgq,acomincq,...,xoptdqp,xopteps12,xoptepsp12,xoptepsq,xoptepsqp,xoptq,xoptqp,xrdq,xsgaq,costat
0,INDL,C,D,STD,AAN,USD,2010Q1,2010Q1,0.0,0.219,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,194.930,A
1,INDL,C,D,STD,AAN,USD,2010Q2,2010Q2,0.0,-0.179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,195.503,A
2,INDL,C,D,STD,AAN,USD,2010Q3,2010Q3,0.0,0.454,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,194.246,A
3,INDL,C,D,STD,AAN,USD,2010Q4,2010Q4,0.0,0.846,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,193.944,A
4,INDL,C,D,STD,AAN,USD,2011Q1,2011Q1,0.0,1.112,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,201.842,A
5,INDL,C,D,STD,AAN,USD,2011Q2,2011Q2,0.0,1.196,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,199.784,A
6,INDL,C,D,STD,AAN,USD,2011Q3,2011Q3,0.0,-0.319,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,206.088,A
7,INDL,C,D,STD,AAN,USD,2011Q4,2011Q4,0.0,0.274,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,208.170,A
8,INDL,C,D,STD,AAN,USD,2012Q1,2012Q1,0.0,0.830,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,221.460,A
9,INDL,C,D,STD,AAN,USD,2012Q2,2012Q2,0.0,-0.091,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,224.673,A
10,INDL,C,D,STD,AAN,USD,2012Q3,2012Q3,0.0,1.304,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,220.767,A
11,INDL,C,D,STD,AAN,USD,2012Q4,2012Q4,0.0,-0.069,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,228.579,A
12,INDL,C,D,STD,AAN,USD,2013Q1,2013Q1,0.0,-0.080,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,235.614,A
13,INDL,C,D,STD,AAN,USD,2013Q2,2013Q2,0.0,-0.086,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,235.868,A
14,INDL,C,D,STD,AAN,USD,2013Q3,2013Q3,0.0,-0.072,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,245.490,A
15,INDL,C,D,STD,AAN,USD,2013Q4,2013Q4,0.0,-0.064,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,248.696,A
16,INDL,C,D,STD,AAN,USD,2014Q1,2014Q1,0.0,-0.068,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,248.638,A
17,INDL,C,D,STD,AAN,USD,2014Q2,2014Q2,0.0,-0.057,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,287.157,A
18,INDL,C,D,STD,AAN,USD,2014Q3,2014Q3,0.0,-0.083,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,300.081,A
19,INDL,C,D,STD,AAN,USD,2014Q4,2014Q4,0.0,-0.090,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,310.325,A
20,INDL,C,D,STD,AAN,USD,2015Q1,2015Q1,0.0,-0.087,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,307.976,A
21,INDL,C,D,STD,AAN,USD,2015Q2,2015Q2,0.0,-0.066,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,305.743,A
22,INDL,C,D,STD,AAN,USD,2015Q3,2015Q3,0.0,-0.222,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,321.590,A
23,INDL,C,D,STD,AAN,USD,2015Q4,2015Q4,0.0,-0.517,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,334.666,A
24,INDL,C,D,STD,AAN,USD,2016Q1,2016Q1,0.0,0.076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,323.998,A
25,INDL,C,D,STD,AAN,USD,2016Q2,2016Q2,0.0,0.169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,310.388,A
26,INDL,C,D,STD,AAN,USD,2016Q3,2016Q3,0.0,-0.072,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.341,A
27,INDL,C,D,STD,AAN,USD,2016Q4,2016Q4,0.0,-0.531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,319.997,A
28,INDL,C,D,STD,AAN,USD,2017Q1,2017Q1,0.0,-0.328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.185,A
29,INDL,C,D,STD,AAN,USD,2017Q2,2017Q2,0.0,0.118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,310.886,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803,INDL,C,D,STD,FOXF,USD,2011Q1,2011Q1,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,A
3804,INDL,C,D,STD,FOXF,USD,2011Q2,2011Q2,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,A
3805,INDL,C,D,STD,FOXF,USD,2011Q3,2011Q3,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,A
3806,INDL,C,D,STD,FOXF,USD,2011Q4,2011Q4,0.0,0.000,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,9.750,29.086,A
3807,INDL,C,D,STD,FOXF,USD,2012Q1,2012Q1,0.0,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.376,7.504,A
3808,INDL,C,D,STD,FOXF,USD,2012Q2,2012Q2,0.0,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.393,8.249,A
3809,INDL,C,D,STD,FOXF,USD,2012Q3,2012Q3,0.0,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.427,7.800,A
3810,INDL,C,D,STD,FOXF,USD,2012Q4,2012Q4,0.0,0.001,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.531,7.807,A
3811,INDL,C,D,STD,FOXF,USD,2013Q1,2013Q1,0.0,-0.006,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.355,8.312,A
3812,INDL,C,D,STD,FOXF,USD,2013Q2,2013Q2,0.0,0.022,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.587,8.881,A
3813,INDL,C,D,STD,FOXF,USD,2013Q3,2013Q3,0.0,0.012,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.500,9.219,A
3814,INDL,C,D,STD,FOXF,USD,2013Q4,2013Q4,0.0,-0.015,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2.967,9.258,A
3815,INDL,C,D,STD,FOXF,USD,2014Q1,2014Q1,0.0,-0.009,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.135,9.884,A
3816,INDL,C,D,STD,FOXF,USD,2014Q2,2014Q2,0.0,-0.006,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.625,12.798,A
3817,INDL,C,D,STD,FOXF,USD,2014Q3,2014Q3,0.0,-0.144,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.468,12.756,A
3818,INDL,C,D,STD,FOXF,USD,2014Q4,2014Q4,0.0,-0.406,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.414,12.066,A
3819,INDL,C,D,STD,FOXF,USD,2015Q1,2015Q1,0.0,-0.472,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,3.402,12.798,A
3820,INDL,C,D,STD,FOXF,USD,2015Q2,2015Q2,0.0,-0.468,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,4.158,15.009,A
3821,INDL,C,D,STD,FOXF,USD,2015Q3,2015Q3,0.0,-1.223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.641,16.257,A
3822,INDL,C,D,STD,FOXF,USD,2015Q4,2015Q4,0.0,-1.953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800,15.763,A
3823,INDL,C,D,STD,FOXF,USD,2016Q1,2016Q1,0.0,-1.119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.392,16.558,A
3824,INDL,C,D,STD,FOXF,USD,2016Q2,2016Q2,0.0,-1.161,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.582,17.920,A
3825,INDL,C,D,STD,FOXF,USD,2016Q3,2016Q3,0.0,-1.348,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.724,18.072,A
3826,INDL,C,D,STD,FOXF,USD,2016Q4,2016Q4,0.0,-2.193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.761,18.573,A
3827,INDL,C,D,STD,FOXF,USD,2017Q1,2017Q1,0.0,-0.941,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.482,19.032,A
3828,INDL,C,D,STD,FOXF,USD,2017Q2,2017Q2,0.0,-0.977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.982,19.877,A
3829,INDL,C,D,STD,FOXF,USD,2017Q3,2017Q3,0.0,-0.632,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.545,21.115,A
3830,INDL,C,D,STD,FOXF,USD,2017Q4,2017Q4,0.0,-0.168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.169,21.324,A
3831,INDL,C,D,STD,FOXF,USD,2018Q1,2018Q1,0.0,0.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.197,23.751,A
3832,INDL,C,D,STD,FOXF,USD,2018Q2,2018Q2,0.0,-1.021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.057,26.333,A

In [18]:
#first try of using describe function
result = data2['xrdq'].describe()
pd.DataFrame(result)

              xrdq
count  1269.000000
mean    241.777066
std     733.505445
min      -0.013000
25%       0.076000
50%       4.200000
75%      45.000000
max    4803.000000

In [19]:
#just select column which dtype is "number"
data2.describe(include=['number'])

,acchgq,acomincq,acoq,actq,altoq,ancq,anoq,aociderglq,aociotherq,aocipenq,...,xoptdq,xoptdqp,xopteps12,xoptepsp12,xoptepsq,xoptepsqp,xoptq,xoptqp,xrdq,xsgaq
count,3593.0,3730.000000,3256.000000,2797.000000,3120.000000,2661.000000,2725.000000,3497.000000,3622.000000,3547.000000,...,2483.0,2409.0,2192.0,2406.0,2483.0,2409.0,2483.0,2409.0,1269.000000,3247.000000
mean,0.0,-379.371032,378.165016,3907.354717,1850.124540,7567.518165,-92.512657,-16.258015,-32.533358,-294.309059,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,241.777066,429.552616
std,0.0,2057.958323,1614.004119,16425.232845,15020.597211,27104.605732,680.304043,292.829947,407.193280,1554.273402,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,733.505445,1463.944620
min,0.0,-23974.000000,0.000000,0.000000,0.000000,0.000000,-8546.000000,-5300.000000,-9231.000000,-22901.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.013000,-923.000000
25%,0.0,-52.082000,1.497500,103.349000,4.527750,56.849000,0.000000,-0.030000,0.000000,-34.897500,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.076000,11.990500
50%,0.0,-4.139500,15.276000,303.133000,26.052000,579.356000,0.000000,0.000000,0.000000,-1.764000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.200000,47.611000
75%,0.0,0.000000,70.648250,1027.400000,166.416500,1290.025000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.000000,152.020500
max,0.0,3757.000000,18681.000000,169662.000000,269166.000000,262984.000000,1136.464000,3079.000000,2715.000000,60.500000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4803.000000,12640.000000

In [20]:
#to count how mnay percentage of missing data for each column
data2.isnull().mean()

indfmt        0.000000
consol        0.000000
popsrc        0.000000
datafmt       0.000000
tic           0.000000
curcdq        0.000000
datacqtr      0.001044
datafqtr      0.000000
acchgq        0.062614
acomincq      0.026872
acoq          0.150535
actq          0.270284
altoq         0.186016
ancq          0.305766
anoq          0.289069
aociderglq    0.087660
aociotherq    0.055048
aocipenq      0.074615
aocisecglq    0.055570
aol2q         0.291156
aoq           0.017480
apq           0.020610
aqaq          0.794678
aqdq          0.795721
aqepsq        0.796504
aqpl1q        0.289851
aqpq          0.770154
arcedq        1.000000
arceepsq      1.000000
arceq         1.000000
                ...
upstkq        0.964519
urectq        0.964519
uspiq         0.964519
usubdvpq      0.976520
usubpcvq      0.969997
utemq         0.983303
wcapq         0.270545
wdaq          0.934777
wddq          0.936081
wdepsq        0.936081
wdpq          0.930864
xaccq         0.553874
xidoq         0.009914
xintq         0.195669
xiq           0.016175
xoprq         0.013566
xopt12        0.428124
xoptd12       0.428124
xoptd12p      0.372293
xoptdq        0.352205
xoptdqp       0.371511
xopteps12     0.428124
xoptepsp12    0.372293
xoptepsq      0.352205
xoptepsqp     0.371511
xoptq         0.352205
xoptqp        0.371511
xrdq          0.668928
xsgaq         0.152883
costat        0.000000
Length: 370, dtype: float64

In [21]:
#use the column which has less than 50% missing data
data3 = data2.loc[:, data1.isnull().mean() < .5]
data4 = data3.describe(include=['number'])
data4

,acchgq,acomincq,acoq,actq,altoq,ancq,anoq,aociderglq,aociotherq,aocipenq,...,xoptd12p,xoptdq,xoptdqp,xopteps12,xoptepsp12,xoptepsq,xoptepsqp,xoptq,xoptqp,xsgaq
count,3593.0,3730.000000,3256.000000,2797.000000,3120.000000,2661.000000,2725.000000,3497.000000,3622.000000,3547.000000,...,2406.0,2483.0,2409.0,2192.0,2406.0,2483.0,2409.0,2483.0,2409.0,3247.000000
mean,0.0,-379.371032,378.165016,3907.354717,1850.124540,7567.518165,-92.512657,-16.258015,-32.533358,-294.309059,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,429.552616
std,0.0,2057.958323,1614.004119,16425.232845,15020.597211,27104.605732,680.304043,292.829947,407.193280,1554.273402,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1463.944620
min,0.0,-23974.000000,0.000000,0.000000,0.000000,0.000000,-8546.000000,-5300.000000,-9231.000000,-22901.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-923.000000
25%,0.0,-52.082000,1.497500,103.349000,4.527750,56.849000,0.000000,-0.030000,0.000000,-34.897500,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.990500
50%,0.0,-4.139500,15.276000,303.133000,26.052000,579.356000,0.000000,0.000000,0.000000,-1.764000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.611000
75%,0.0,0.000000,70.648250,1027.400000,166.416500,1290.025000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,152.020500
max,0.0,3757.000000,18681.000000,169662.000000,269166.000000,262984.000000,1136.464000,3079.000000,2715.000000,60.500000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12640.000000

In [22]:
#for counting the missing
data3.isnull().sum()
data_final = data4.append(data3.isnull().sum(), ignore_index=True)
data_final.rename(index={0:'observations',1:'mean',2:'std',3:'min',4:'p25',5:'Median',6:'P75',7:'Max',8:'Missing'}, inplace=True)
data_final

,acchgq,acomincq,acoq,actq,altoq,ancq,anoq,aociderglq,aociotherq,aocipenq,...,xsgaq,consol,costat,curcdq,datacqtr,datafmt,datafqtr,indfmt,popsrc,tic
observations,3593.0,3730.000000,3256.000000,2797.000000,3120.000000,2661.000000,2725.000000,3497.000000,3622.000000,3547.000000,...,3247.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.0,-379.371032,378.165016,3907.354717,1850.124540,7567.518165,-92.512657,-16.258015,-32.533358,-294.309059,...,429.552616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.0,2057.958323,1614.004119,16425.232845,15020.597211,27104.605732,680.304043,292.829947,407.193280,1554.273402,...,1463.944620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.0,-23974.000000,0.000000,0.000000,0.000000,0.000000,-8546.000000,-5300.000000,-9231.000000,-22901.000000,...,-923.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
p25,0.0,-52.082000,1.497500,103.349000,4.527750,56.849000,0.000000,-0.030000,0.000000,-34.897500,...,11.990500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median,0.0,-4.139500,15.276000,303.133000,26.052000,579.356000,0.000000,0.000000,0.000000,-1.764000,...,47.611000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P75,0.0,0.000000,70.648250,1027.400000,166.416500,1290.025000,0.000000,0.000000,0.000000,0.000000,...,152.020500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max,0.0,3757.000000,18681.000000,169662.000000,269166.000000,262984.000000,1136.464000,3079.000000,2715.000000,60.500000,...,12640.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Missing,240.0,103.000000,577.000000,1036.000000,713.000000,1172.000000,1108.000000,336.000000,211.000000,286.000000,...,586.000000,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0